config/routes.rb
Rails.application.routes.draw do
  resources :courses do
    resources :examinations do
      resources :scores, only: [:index]
      patch 'scores/edit', to: 'scores#update' 
    end
    resources :students, except: [:show]
  end

  devise_for :users, skip: :all

  # if user authenticated then root is courses page
  authenticated :user do
    root 'courses#index', as: :authenticated_root
  end

  #Change default devise routes
  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new', as: :new_user_session
    post 'sign_in', to: 'devise/sessions#create', as: :user_session
    delete 'sign_out', to: 'devise/sessions#destroy', as: :destroy_user_session
    root to: redirect('/sign_in')
  end

  patch 'set_locale', to: 'locale#set_locale'
  match "/404", :to => "errors#not_found", :via => :all, :as => :not_found
  match "/500", :to => "errors#internal_server_error", :via => :all

end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :examination
  belongs_to :student

  validates :score, presence: true,
                    format: { with: /\A\d+(?:\.\d{0,2})?\z/,
                              message: :decimal_msg },
                    numericality: { greater_than_or_equal_to: 0,
                                    less_than_or_equal_to: 100 }

  validates :examination, uniqueness: { scope: :student }
  validates :student, uniqueness: { scope: :examination }

  def passed?
    if score.present?
      score >= examination.min_score
    else
      false
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_examination, only: %i[index update]

  before_action :build_scores, only: [:index]

  def update
    @examination.assign_attributes(score_params)
    if @examination.save
      delete_scores
      redirect_to course_examination_scores_path(@examination.course, @examination),
                  notice: (t :updated_scores)
    else
      build_scores
      render :index
    end
  end

  private

  def set_examination
    @examination = Examination.find(params[:examination_id])
  end

  def build_scores
    @examination.course.students.each do |student|
      @examination.scores.build(student: student) unless student.took_exam?(@examination)
    end
  end

  def score_params
    params.require(:examination).permit(scores_attributes: %i[score id student_id])
  end

  def delete_scores
    score_params.fetch(:scores_attributes).each do |_key, score|
      Score.find(score['id']).destroy if score['id'] && score['score'].empty?
    end
  end
end

app/views/scores/_form.html.erb
<div class="card-form xl">
  <div class="card">
    <div class="card-body">
      <h5><%= t(@title) %></h5> 
      <hr>
      <%= simple_form_for [@score], html: {data: { course: @course.id }} do |f| %>
          <div class="form-group">
             <%= f.association :examination, 
                  collection: @course.examinations,
                  :include_blank => t(:select_examination) %>
          </div>
          <div class="form-group">
            <%= f.association :student,
                collection: [], group_method: :student, 
                include_blank: t(:select_student) %>
          </div>
          <div class="form-group">
            <%= f.input :score, placeholder: "#{t(:score)} #{t(:in_percentage)}" %>
          </div>
          <div class="form-actions text-right">
            <%= link_to t(:cancel), scores_path, class: "btn btn-default" %>
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
      <% end %>
    </div>
  </div>
  </div>

app/views/scores/edit.html.erb
<div class="card card-table">
  <div class="card-body container">
    <h1><%= t(:new_score) %></h1> 
    <hr>
    <%= simple_form_for @examination, 
        url: course_examination_scores_edit_path(@course, @examination), 
        method: :post,  html: { id: :edit_scores } do |f| %>
      <div class="card-btns">
      <%= link_to_add_association 'add address', f, :scores, class: "btn btn-primary float-right btn-sm",       
        'data-association-insertion-method' => 'append',
        'data-association-insertion-node' => 'tbody'  %>
      </div>
      <table class="table">
        <thead>
          <th><%= t :name %></th>
          <th><%= t :s_number %></th>
          <th><%= t :score %></th>
        </thead>
        <tbody>
          <%= f.fields_for :scores do |score| %>
            <tr class="nested-fields">
            <td>
            <div class="form-group"> 
              <%= score.association :student, as: :display, association_label: 'full_name', label: false %>
            </div> 
            </td>
            <td>
            <div class="form-group"> 
              <%= score.association :student, as: :display, association_label: 's_number', label: false %>
            </div> 
            </td>
            <td>
            <div class="form-group">    
                <%= score.input :score, placeholder: t(:min_score) + ' ' + t(:in_percentage), label: false  %>
            </div>
            </td>
            </tr>
          <% end %>
        </tbody>
        </table>
          <div class="form-actions text-right">
            <%= link_to t(:cancel), course_examination_scores_path(@course, @examination), class: "btn btn-default" %>
            <%= f.button :submit, class: "btn btn-primary" %>
          </div>
    <% end %>
 </div>
</div>

app/views/scores/index.html.erb
<% content_for :back do %>
  <%= link_to course_examinations_path(@examination.course), class: "btn btn-default float-right", :title => (t(:back)) do %>
    <%= fa_icon "reply" %>
  <% end %>
<% end %>

<% content_for :subtitle do %>
  <%= @examination.title %> -
  <%= link_to course_title(@examination.course), course_path(@examination.course), class: "black"  %>
<% end %>

<% content_for :no_results do %>
  <%= render 'layouts/no_results', title: :no_students, icon: "book", 
  path: new_course_student_path(@examination.course), text: :new_student   %>
<% end %>

<% content_for :btns do %>
  <button class="btn btn btn-primary btn-sm float-right" id="edit-btn">
    <%= t :edit_scores %>
  </button>
<% end %>

<% content_for :form do %>
  <%= simple_form_for @examination, 
  url: course_examination_scores_edit_path(@examination.course, @examination), 
  method: :patch,  html: { id: :edit_scores } do |f| %>
    <div class="table-responsive">
    <table class="table table-striped text-center">
      <thead>
        <th><%= t :surname %></th>
        <th><%= t :name %></th>
        <th><%= t :s_number %></th>
        <th><%= t :status %></th>
        <th><%= t :score_in_percentage %></th>
      </thead>
      <tbody>
        <%= f.fields_for :scores, @examination.scores.sort_by{|e| e.student.surname } do |score| %>
          <tr class="nested-fields">
            <td>
              <%= score.object.student.surname %>
            </td>
            <td>
              <%= score.object.student.name %>
            </td>
            <td>
              <%= score.object.student.s_number %>
            </td>
            <td>
              <% if score.object.score.present? && score.object.passed? %>
                <span class="text-success"><%= t :passed %></span>
              <% elsif score.object.score.present? %>
                <span class="text-danger"><%= t :failed %></span>
              <% else %>
                <span class="text-warning"><%= t :absent %></span>
              <% end %>
            </td>
            <td>  
              <%= score.input :score, label: false, 
                placeholder: (t :not_loaded),
                required: false,
                input_html: {step: "0.01", 
                            disabled: "true", 
                            class: "table-input"}  
              %>
              <%= score.hidden_field :student_id %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    </div>
    <br>
    <div class="form-actions text-right">
      <%= link_to (t :cancel), 
        course_examination_scores_path(@examination.course, @examination),
        class: "btn btn-secondary hide", 
        id:"cancel-btn" 
      %>
      <%= f.button :submit, (t :upload_scores), 
          class: "btn btn-primary hide",
          id: "submit-btn" 
      %>
    </div>
  <% end %>
<% end %>

<%= render 'layouts/contentCard', card_title: t(:scores), collection: @examination.scores %>